![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [51]:
# Import libraries
import pandas as pd

# Load the CSV file.
schools = pd.read_csv("schools.csv")

# Save your results in a pandas DataFrame called best_math_schools, including "school_name" and "average_math" columns, sorted by "average_math" in descending order.

best_math_schools = schools[schools["average_math"] >= 0.8 * 800][["school_name", "average_math"]].sort_values("average_math", ascending= False)
schools["total_SAT"] = schools["average_math"] + schools["average_writing"]+ schools["average_reading"]

# Save your results as a pandas DataFrame called top_10_schools containing the "school_name" and a new column named "total_SAT", with results ordered by "total_SAT" in descending order.

top_10_schools = schools[["school_name","total_SAT"]].sort_values("total_SAT", ascending=False).head(10)

# Which single borough has the largest standard deviation in the combined SAT score? Save your results as a pandas DataFrame called largest_std_dev. Round all numeric values to two decimal places.

std_dev_by_borough = schools.groupby("borough")["total_SAT"].agg(['std', 'mean','count']).reset_index()

std_dev_by_borough.columns = ["borough", "std_SAT", "average_SAT", "num_schools"]

largest_std_dev["std_SAT"] = largest_std_dev["std_SAT"].round(2)

std_dev_by_borough = std_dev_by_borough.sort_values("std_SAT",ascending=False)
largest_std_dev = std_dev_by_borough.head(1).round(2)

largest_std_dev.columns = ["borough", "std_SAT", "average_SAT", "num_schools"]

largest_std_dev.head()

     borough  std_SAT  average_SAT  num_schools
2  Manhattan   230.29      1340.13           89